<?php

include('class_sugerencias.php');
include('class_conexion.php');

class sugerencias_dal extends class_db
{
    function __construct()
    {
        parent::__construct();
    }

    function __destruct()
    {
        parent::__destruct(); // TODO: Change the autogenerated stub
    }

    //insert
    function insert_sugerencia($titulo, $remitente, $emailRemit, $telRemit, $asunto)
    {
        $insert_sugerencia = "INSERT INTO sugerencias (titulo_sugerencia, remitente_sugerencia,
                              email_remitente_sugerencia, tel_remitente_sugerencia, asunto_sugerencia) VALUES (";
        $insert_sugerencia .= "'" . $titulo . "',";
        $insert_sugerencia .= "'" . $remitente . "',";
        $insert_sugerencia .= "'" . $emailRemit . "',";
        $insert_sugerencia .= "'" . $telRemit . "',";
        $insert_sugerencia .= "'" . $asunto . "')";
        //print $insert_sugerencia; exit;

        $this->set_sql($insert_sugerencia);
        $this->db_conn->set_charset('utf8');

        mysqli_query($this->db_conn, $this->db_query) or die(mysqli_error($this->db_conn));

        if (mysqli_affected_rows($this->db_conn) == 1) {
            $inserted = 1;
        } else {
            $inserted = 0;
        }

        return $inserted;
    }

    //update
    function update_sugerencia($idSugerencia, $titulo, $remitente, $emailRemit, $telRemit, $asunto)
    {
        $update_sugerencia = "UPDATE sugerencias SET ";
        $update_sugerencia .= "'" . $titulo . "',";
        $update_sugerencia .= "'" . $remitente . "',";
        $update_sugerencia .= "'" . $emailRemit . "',";
        $update_sugerencia .= "'" . $telRemit . "',";
        $update_sugerencia .= "'" . $asunto . "'";
        $update_sugerencia .= " WHERE id_sugerencia = $idSugerencia";
        //print $update_sugerencia; exit;

        $this->set_sql($update_sugerencia);
        $this->db_conn->set_charset('utf8');

        mysqli_query($this->db_conn, $this->db_query) or die(mysqli_error($this->db_conn));

        if (mysqli_affected_rows($this->db_conn) == 1) {
            $updated = 1;
        } else {
            $updated = 0;
        }

        return $updated;
    }

    //delete
    function delete_sugerencia($idSugerencia)
    {
        $delete_sugerencia = "DELETE FROM sugerencias WHERE id_sugerencia = $idSugerencia";
        //print $delete_sugerencia; exit;

        $this->set_sql($delete_sugerencia);
        $this->db_conn->set_charset('utf8');

        mysqli_query($this->db_conn, $this->db_query) or die(mysqli_error($this->db_conn));

        if (mysqli_affected_rows($this->db_conn) == 1) {
            $deleted = 1;
        } else {
            $deleted = 0;
        }

        return $deleted;
    }

    //select all
    function select_sugerencias()
    {
        $select_sugerencias = "SELECT * FROM sugerencias";
        //print $select_sugerencias; exit;

        $this->set_sql($select_sugerencias);
        $this->db_conn->set_charset('utf8');

        $result = mysqli_query($this->db_conn, $this->db_query) or die(mysqli_error($this->db_conn));
        $total_result = mysqli_num_rows($result);

        $counter = 0;
        while ($row = mysqli_fetch_assoc($result)) {
            $object = new sugerencias;

            /*los nombres entre comillas son los nombres de las columnas de las tablas
            se usan los set para enviar el valor al objeto y con el get obtenemos el valor
            donde lo invoquemos*/
            $object->setIdSugerencia($row["id_sugerencia"]);
            $object->setRemitenteSugerencia($row["remitente_sugerencia"]);
            $object->setEmailRemitenteSugerencia($row["email_remitente_sugerencia"]);
            $object->setTelRemitenteSugerencia($row["tel_remitente_sugerencia"]);
            $object->setTituloSugerencia($row["titulo_sugerencia"]);
            $object->setAsuntoSugerencia($row["asunto_sugerencia"]);

            $counter++;
            $list[$counter] = $object;
            unset($object);
        }
        return $list;
    }

    //select by id_sugerencia
    function select_by_idsugerencia($id)
    {
        $select_by_idsugerencia = "SELECT * FROM sugerencias WHERE id_sugerencia = $id";
        //print $select_by_idsugerencia; exit;

        $this->set_sql($select_by_idsugerencia);
        $this->db_conn->set_charset('utf8');

        $result = mysqli_query($this->db_conn, $this->db_query) or die(mysqli_error($this->db_conn));
        $total_result = mysqli_num_rows($result);

        $object = null;
        $row = mysqli_fetch_assoc($result);

        if ($total_result > 0) {
            $object = new sugerencias(
                $row["id_sugerencia"],
                utf8_encode($row["remitente_sugerencia"]),
                utf8_encode($row["email_remitente_sugerencia"]),
                utf8_encode($row["tel_remitente_sugerencia"]),
                utf8_encode($row["titulo_sugerencia"]),
                utf8_encode($row["asunto_sugerencia"])
            );
        }
        return $object;
    }
}