<?php

include('class_conexion.php');
include('class_noticias.php');

class noticias_dal extends class_db
{

    /**
     * noticias_dal constructor.
     */
    public function __construct()
    {
        parent::__construct();
    }

    public function __destruct()
    {
        parent::__destruct(); // TODO: Change the autogenerated stub
    }

    //insert
    function insert_noticia($titulo, $desc, $img)
    {
        $insert_noticia = "INSERT INTO noticias(titulo_noticia, descripcion_noticia, imagen_noticia)";
        $insert_noticia .= " VALUES (";
        $insert_noticia .= "'" . $titulo . "',";
        $insert_noticia .= "'" . $desc . "',";
        $insert_noticia .= "'" . $img . "')";
        //print $insert_noticia; exit;

        $this->set_sql($insert_noticia);
        $this->db_conn->set_charset('utf8');

        mysqli_query($this->db_conn, $this->db_query) or die(mysqli_error($this->db_conn));

        if (mysqli_affected_rows($this->db_conn) == 1) {
            $insertados = 1;
        } else {
            $insertados = 0;
        }

        return $insertados;
    }

    function update_noticia($id_noticia, $descripcion_noticia){
        $update_producto = "UPDATE noticias SET ";
        $update_producto .= "descripcion_noticia = '$descripcion_noticia'";
        $update_producto .= "WHERE id_noticia = $id_noticia";
        //print $update_producto; exit;

        $this->set_sql($update_producto);
        $this->db_conn->set_charset('utf8');

        mysqli_query($this->db_conn, $this->db_query) or die(mysqli_error($this->db_conn));

        if (mysqli_affected_rows($this->db_conn) == 1) {
            $updated = 1;
        } else {
            $updated = 0;
        }
        unset($object);
        return $updated;
    }
    

    //delete
    function delete_noticia($idNoticia)
    {
        $delete_noticia = "DELETE FROM noticias WHERE id_noticia = $idNoticia";
        //print $delete_noticia; exit;

        $this->set_sql($delete_noticia);
        $this->db_conn->set_charset('utf8');

        mysqli_query($this->db_conn, $this->db_query) or die(mysqli_error($this->db_conn));

        if (mysqli_affected_rows($this->db_conn) == 1) {
            $borrados = 1;
        } else {
            $borrados = 0;
        }

        return $borrados;
    }

    function select_noticias()
    {
        $select_noticias = "SELECT * FROM noticias";
        //print $select_productos; exit;

        $this->set_sql($select_noticias);
        $this->db_conn->set_charset('utf8');

        $result = mysqli_query($this->db_conn, $this->db_query) or die(mysqli_error($this->db_conn));
        $total_result = mysqli_num_rows($result);

        $counter = 0;
        while ($row = mysqli_fetch_assoc($result)) {
            $object = new noticias();

            /*los nombres entre comillas son los nombres de las columnas de las tablas
            se usan los set para enviar el valor al objeto y con el get obtenemos el valor
            donde lo invoquemos*/
            $object->setIdNoticia($row["id_noticia"]);
            $object->setTituloNoticia($row["titulo_noticia"]);
            $object->setDescripcionNoticia($row["descripcion_noticia"]);
            $object->setImagenNoticia($row["imagen_noticia"]);
           
            $counter++;
            $list[$counter] = $object;
            unset($object);
        }
        return $list;
    }

    function count_noticas(){
        $select_noticias = "SELECT COUNT(id_noticia) FROM noticias";
        $this->set_sql($select_noticias);
        $this->db_conn->set_charset('utf8');

        $result = mysqli_query($this->db_conn, $this->db_query) or die(mysqli_error($this->db_conn));
        $total_result = mysqli_num_rows($result);

        return $total_result;

    }

    function select_by_idnoticia($id){
        $select_id_producto = "SELECT * FROM noticias WHERE id_noticia = $id";
        //print $select_id_producto; exit;

        $this->set_sql($select_id_producto);
        $this->db_conn->set_charset('utf8');

        $result = mysqli_query($this->db_conn, $this->db_query) or die(mysqli_error($this->db_conn));
        $total_result = mysqli_num_rows($result);

        //$object = null;
        $i=0;
        while($renglon = mysqli_fetch_assoc($result)) {
                   $obj_det = new noticias($renglon["id_noticia"],
                   utf8_encode($renglon["titulo_noticia"]),
                   utf8_encode($renglon["descripcion_noticia"]),
                   $renglon["imagen_noticia"]);
            $i++;
            $lista[$i]=$obj_det;
            unset($obj_det);
        }
        mysqli_free_result($result);    
        return $lista;
    }
}